[package]
authors = ["guillem.cordoba@gmail.com"]
build = "build.rs"
default-run = "holochain-launcher"
description = "Holochain launcher to run Holochain locally in your desktop"
edition = "2018"
license = ""
name = "holochain-launcher"
repository = ""
version = "0.3.10"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = {version = "1.0.0-rc.4", features = []}

[dependencies]
async-trait = "0.1.52"
base64 = "0.13.0"
chrono = {version = "0.4", features = ["serde"]}
flate2 = "1.0.20"
futures = "0.3"
holochain_client_0_0_130 = {package = "holochain_client", git = "https://github.com/holochain/holochain-client-rust", rev = "9f7b9525c5dc9913d9e7f78b257da26ba7a076a8"}
holochain_conductor_api_0_0_130 = {package = "holochain_conductor_api", version = "0.0.30"}
holochain_p2p_0_0_130 = {package = "holochain_p2p", version = "0.0.30"}
holochain_types_0_0_130 = {package = "holochain_types", version = "0.0.30"}
holochain_websocket_0_0_130 = {package = "holochain_websocket", version = "0.0.30"}
log = "0.4.14"
log4rs = "1.0.0"
mr_bundle = "0.0.8"
open = "2.0.1"
opener = "0.5.0"
portpicker = "0.1.1"
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
serde_yaml = "0.8"
tauri = {version = "1.0.0-rc.4", features = ["api-all", "system-tray"]}
url2 = "0.0.6"
zip = "0.5.0"

[features]
custom-protocol = ["tauri/custom-protocol"]
default = ["custom-protocol"]
