[package]
authors = ["guillem.cordoba@gmail.com"]
build = "src/build.rs"
default-run = "holochain-launcher"
description = "A Tauri App"
edition = "2018"
license = ""
name = "holochain-launcher"
repository = ""
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = {path = "../../../../tauri/core/tauri-build"}

[dependencies]
base64 = "0.13.0"
chrono = {version = "0.4", features = ["serde"] }
edit = "0.1.3"
flate2 = "1.0.20"
futures = "0.3"
holochain_conductor_api_rust = {git = "https://github.com/holochain/conductor-api-rust", rev = "4edf406b674d676f076bb19fdbe79fe5a1077c0d"}
log = "0.4.14"
log4rs = "1.0.0"
open = "1"
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
tauri = {path = "../../../../tauri/core/tauri", features = ["api-all", "menu", "system-tray"] }
zip = "0.5"

[features]
custom-protocol = ["tauri/custom-protocol"]
default = ["custom-protocol"]

[patch.crates-io]
hdk_derive = {git = "https://github.com/holochain/holochain", rev = "753ea0873cd6e4c7b3ba30ead2d815d5f61b5373", package = "hdk_derive"}
holo_hash = {git = "https://github.com/holochain/holochain", rev = "753ea0873cd6e4c7b3ba30ead2d815d5f61b5373", package = "holo_hash"}
holochain_zome_types = {git = "https://github.com/holochain/holochain", rev = "753ea0873cd6e4c7b3ba30ead2d815d5f61b5373", package = "holochain_zome_types"}
lmdb-rkv = {git = "https://github.com/holochain/lmdb-rs.git"}
rkv = {git = "https://github.com/holochain/rkv.git", branch = "master"}

tao = {git = "https://github.com/tauri-apps/tao", rev = "01fc43b05ea41463d512c0e3497971edc543ac9d"}
