[package]
authors = ["guillem.cordoba@gmail.com"]
build = "build.rs"
default-run = "holochain-launcher"
description = "Holochain launcher to run Holochain locally in your desktop"
edition = "2018"
license = ""
name = "holochain-launcher"
repository = ""
version = "0.2.3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
# Branch `next`
tauri-build = {git = "https://github.com/tauri-apps/tauri", rev = "bb00d5bd6c9dfcb6bdd0d308dadb70e6c6aafe5c"}

[dependencies]
base64 = "0.13.0"
chrono = {version = "0.4", features = ["serde"] }
flate2 = "1.0.20"
futures = "0.3"
holochain_conductor_client = {git = "https://github.com/holochain/conductor-client-rust", rev = "53bb9925e29443fe727926ab27c07e1b1ea51e3f"}
holochain_types = "0.0.7"
log = "0.4.14"
log4rs = "1.0.0"
mr_bundle = "0.0.4"
open = "2.0.1"
opener = "0.5.0"
serde = {version = "1", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
# Branch `next`
portpicker = "0.1.1"
tauri = {git = "https://github.com/tauri-apps/tauri", rev = "bb00d5bd6c9dfcb6bdd0d308dadb70e6c6aafe5c", features = ["api-all", "system-tray"] }
zip = "0.5.0"

[features]
custom-protocol = ["tauri/custom-protocol"]
default = ["custom-protocol"]
