[package]
authors = ["guillem.cordoba@gmail.com"]
build = "src/build.rs"
default-run = "holochain-launcher"
description = "Holochain launcher to run Holochain locally in your desktop"
edition = "2018"
license = ""
name = "holochain-launcher"
repository = ""
version = "0.2.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
# Branch `next`
tauri-build = {git = "https://github.com/tauri-apps/tauri", rev = "84f6e3e84a34b01b7fa04f5c4719acb921ef4263"}

[dependencies]
base64 = "0.13.0"
chrono = {version = "0.4", features = ["serde"] }
flate2 = "1.0.20"
futures = "0.3"
holochain_conductor_client = {git = "https://github.com/holochain/conductor-client-rust", rev = "ada5c7444e725ef113a73834ae79950ad66630c2"}
holochain_types = {git = "https://github.com/holochain/holochain", rev = "fa6f19ef2f7586cd0afa6a0103d9a937729eeb9e"}
log = "0.4.14"
log4rs = "1.0.0"
mr_bundle = "0.0.3"
opener = "0.5.0"
serde = {version = "1", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
# Branch `next`
tauri = {git = "https://github.com/tauri-apps/tauri", rev = "84f6e3e84a34b01b7fa04f5c4719acb921ef4263", features = ["api-all", "system-tray"] }
tokio = "1.9.0"
zip = "0.5.0"

[features]
custom-protocol = ["tauri/custom-protocol"]
default = ["custom-protocol"]
