[package]
authors = ["guillem.cordoba@gmail.com"]
build = "src/build.rs"
default-run = "holochain-launcher"
description = "A Tauri App"
edition = "2018"
license = ""
name = "holochain-launcher"
repository = ""
version = "0.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = {git = "https://github.com/tauri-apps/tauri", package = "tauri-build", rev = "74e36c21dd1e3e12830bdc31dbb5fa54c13ad425"}

[dependencies]
base64 = "0.13.0"
chrono = {version = "0.4", features = ["serde"] }
flate2 = "1.0.20"
futures = "0.3"
holochain_conductor_client = {git = "https://github.com/holochain/conductor-client-rust", branch = "main"}
log = "0.4.14"
log4rs = "1.0.0"
open = "1"
open-file = "0.1.0"
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
tauri = {git = "https://github.com/tauri-apps/tauri", package = "tauri", rev = "74e36c21dd1e3e12830bdc31dbb5fa54c13ad425", features = ["api-all", "menu", "system-tray"] }
tokio = "1.7.0"
zip = "0.5"

[features]
custom-protocol = ["tauri/custom-protocol"]
default = ["custom-protocol"]
