[package]
authors = ["guillem.cordoba@gmail.com"]
build = "build.rs"
default-run = "holochain-launcher"
description = "Holochain launcher to run Holochain locally in your desktop"
edition = "2018"
license = ""
name = "holochain-launcher"
repository = ""
version = "0.3.5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
# Branch `next`
tauri-build = {git = "https://github.com/tauri-apps/tauri", rev = "80ffa87edbce52983f01542e266a99fef744f510"}

[dependencies]
base64 = "0.13.0"
chrono = {version = "0.4", features = ["serde"] }
flate2 = "1.0.20"
futures = "0.3"
holochain_conductor_api = "0.0.12"
holochain_conductor_client = {git = "https://github.com/holochain/conductor-client-rust", rev = "ed8bc0efbb7bdc5fd5aa2e922d316f1d03d96410"}
holochain_types = "0.0.12"
holochain_websocket = "0.0.12"
log = "0.4.14"
log4rs = "1.0.0"
mr_bundle = "0.0.4"
open = "2.0.1"
opener = "0.5.0"
portpicker = "0.1.1"
serde = {version = "1", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
# Branch `next`
tauri = {git = "https://github.com/tauri-apps/tauri", rev = "80ffa87edbce52983f01542e266a99fef744f510", features = ["api-all", "system-tray"] }
url = "2.2.2"
zip = "0.5.0"

[features]
custom-protocol = ["tauri/custom-protocol"]
default = ["custom-protocol"]
