[package]
edition = "2021"
name = "lair_keystore_manager"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

ascii = "1.0.0"
async-trait = "0.1.52"
log = "0.4.14"
serde = {version = "1", features = ["derive"]}
serde-enum-str = "0.2"
tauri = {git = "https://github.com/tauri-apps/tauri", rev = "447370fa50a82f8086554086ca9038f4a008a456", features = ["api-all", "system-tray", "native-tls-vendored", "reqwest-native-tls-vendored"]}
thiserror = "1.0.30"
url2 = "0.0.6"
