[package]
name = "holochain_launcher_utils"
version = "0.0.5"
edition = "2021"
description = "Shared utils used by Holochain Launcher and the hc launch CLI (holochain_cli_launch)"
license-file = "LICENSE_CAL-1.0"
homepage = "https://developer.holochain.org"
documentation = "https://docs.rs/holochain_launcher_utils"
repository = "https://github.com/holochain/launcher"
readme = "README.md"
categories = ["command-line-utilities", "development-tools"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

holochain_client = { git = "https://github.com/holochain/holochain-client-rust", branch = "holochain-0.2.0-beta-rc.2" }

holochain_conductor_api = { git = "https://github.com/holochain/holochain", package = "holochain_conductor_api", rev = "352bcebe41808b0a5c58cc6f1ed1e1c96149d010" }
holochain_types = { git = "https://github.com/holochain/holochain", package = "holochain_types", rev = "352bcebe41808b0a5c58cc6f1ed1e1c96149d010" }
holochain_zome_types = { git = "https://github.com/holochain/holochain", package = "holochain_zome_types", rev = "352bcebe41808b0a5c58cc6f1ed1e1c96149d010" }

lair_keystore_api = "0.2.3"


log = "0.4.14"
mime_guess = "2.0.4"
open = "2.0.1"
serde = { version = "1.0", features = ["derive"] }
tauri = {version = "1.2.3", features = ["clipboard-write-text", "dialog-all", "devtools", "native-tls-vendored", "reqwest-native-tls-vendored"] }

