[package]
edition = "2021"
name = "holochain_manager"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
holochain_client = {package = "holochain_client", git = "https://github.com/holochain/holochain-client-rust", rev = "d647cc6c759e404df70cb497950b676e3498ca9b"}

holochain_conductor_api_0_0_127 = {git = "https://github.com/guillemcordoba/holochain", package = "holochain_conductor_api", rev = "a60f227e75d510a2afc1914fdcedd6ebf754ea29"}
holochain_p2p_0_0_127 = {git = "https://github.com/guillemcordoba/holochain", package = "holochain_p2p", rev = "a60f227e75d510a2afc1914fdcedd6ebf754ea29"}
holochain_types_0_0_127 = {git = "https://github.com/guillemcordoba/holochain", package = "holochain_types", rev = "a60f227e75d510a2afc1914fdcedd6ebf754ea29"}

holochain_conductor_api_0_0_131 = {git = "https://github.com/guillemcordoba/holochain", package = "holochain_conductor_api", rev = "af5db7e7f8ab77b95ed34ec8ed5ab3c733148e5e"}
holochain_p2p_0_0_131 = {git = "https://github.com/guillemcordoba/holochain", package = "holochain_p2p", rev = "af5db7e7f8ab77b95ed34ec8ed5ab3c733148e5e"}
holochain_types_0_0_131 = {git = "https://github.com/guillemcordoba/holochain", package = "holochain_types", rev = "af5db7e7f8ab77b95ed34ec8ed5ab3c733148e5e"}

# NEW_VERSION: Copy and paste these lines, upgrading the crates version
# See the appropriate crate version for your holochain version in https://github.com/holochain/holochain/blob/develop/CHANGELOG.md
holochain_conductor_api_0_0_132 = {git = "https://github.com/guillemcordoba/holochain", package = "holochain_conductor_api", rev = "daad7d1e704547d85a58ecd4ae94949b52b91166"}
holochain_p2p_0_0_132 = {git = "https://github.com/guillemcordoba/holochain", package = "holochain_p2p", rev = "daad7d1e704547d85a58ecd4ae94949b52b91166"}
holochain_types_0_0_132 = {git = "https://github.com/guillemcordoba/holochain", package = "holochain_types", rev = "daad7d1e704547d85a58ecd4ae94949b52b91166"}

holochain_conductor_api_0_0_136 = {git = "https://github.com/guillemcordoba/holochain", package = "holochain_conductor_api", rev = "92f56b77d7914e99e4a2a600b372e960426af119"}
holochain_p2p_0_0_136 = {git = "https://github.com/guillemcordoba/holochain", package = "holochain_p2p", rev = "92f56b77d7914e99e4a2a600b372e960426af119"}
holochain_types_0_0_136 = {git = "https://github.com/guillemcordoba/holochain", package = "holochain_types", rev = "92f56b77d7914e99e4a2a600b372e960426af119"}

holochain_conductor_api_0_0_139 = {package = "holochain_conductor_api", version = "0.0.39"}
holochain_p2p_0_0_139 = {package = "holochain_p2p", version = "0.0.37"}
holochain_types_0_0_139 = {package = "holochain_types", version = "0.0.37"}

holochain_conductor_api_0_0_141 = {package = "holochain_conductor_api", version = "0.0.41"}
holochain_p2p_0_0_141 = {package = "holochain_p2p", version = "0.0.39"}
holochain_types_0_0_141 = {package = "holochain_types", version = "0.0.39"}

mr_bundle_0_0_9 = {package = "mr_bundle", version = "0.0.9"}

lair_keystore_manager = {path = "../lair_keystore_manager"}

ascii = "1.0.0"
async-trait = "0.1.52"
enum_dispatch = "0.3.8"
log = "0.4.14"
portpicker = "0.1.1"
serde = {version = "1", features = ["derive"]}
serde-enum-str = "0.2"
serde_yaml = "0.8"
tauri = {version = "=1.0.0-rc.10", features = ["api-all", "gtk-tray", "system-tray"]}
thiserror = "1.0.30"
url2 = "0.0.6"
