[package]
edition = "2021"
name = "holochain_manager"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
holochain_client = {package = "holochain_client", git = "https://github.com/holochain/holochain-client-rust", rev = "77fae4a989fd75d5a01580e0226f733a65a1716f"}

holochain_conductor_api_0_0_127 = {package = "holochain_conductor_api", version = "0.0.27"}
holochain_p2p_0_0_127 = {package = "holochain_p2p", version = "0.0.27"}
holochain_types_0_0_127 = {package = "holochain_types", version = "0.0.27"}
holochain_websocket_0_0_127 = {package = "holochain_websocket", version = "0.0.27"}

holochain_conductor_api_0_0_132 = {package = "holochain_conductor_api", version = "0.0.32"}
holochain_p2p_0_0_132 = {package = "holochain_p2p", version = "0.0.32"}
holochain_types_0_0_132 = {package = "holochain_types", version = "0.0.32"}
holochain_websocket_0_0_132 = {package = "holochain_websocket", version = "0.0.32"}

lair_keystore_manager = {path = "../lair_keystore_manager"}

mr_bundle_0_0_9 = {package = "mr_bundle", version = "0.0.9"}

ascii = "1.0.0"
async-trait = "0.1.52"
enum_dispatch = "0.3.8"
log = "0.4.14"
portpicker = "0.1.1"
serde = {version = "1", features = ["derive"]}
serde-enum-str = "0.2"
serde_yaml = "0.8"
tauri = {version = "1.0.0-rc.6", features = ["api-all", "system-tray"]}
thiserror = "1.0.30"
url2 = "0.0.6"
