[package]
edition = "2021"
name = "holochain_manager"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

holochain_client = { git = "https://github.com/holochain/holochain-client-rust", branch="hc-0.0.172"}


# NEW_VERSION add latest crates here

holochain_conductor_api_0_0_172 = {package = "holochain_conductor_api", version = "0.0.69"}
holochain_p2p_0_0_172 = {package = "holochain_p2p", version = "0.0.66"}
holochain_types_0_0_172 = {package = "holochain_types", version = "0.0.66"}

mr_bundle = {package = "mr_bundle", version = "0.0.13"}

lair_keystore_manager = {path = "../lair_keystore_manager"}

ascii = "1.0.0"
async-trait = "0.1.52"
enum_dispatch = "0.3.8"
log = "0.4.14"
portpicker = "0.1.1"
serde = {version = "1", features = ["derive"]}
serde-enum-str = "0.2"
serde_yaml = "0.8"
tauri = {version = "1.1.1", features = ["api-all", "system-tray", "native-tls-vendored", "reqwest-native-tls-vendored"]}
thiserror = "1.0.30"
url2 = "0.0.6"
