[package]
edition = "2021"
name = "holochain_manager"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# NEW_VERSION update holochain-client-rust to the latest holochain version
holochain_client = {git = "https://github.com/matthme/holochain-client-rust", rev = "b109ef93a8653bc538183ca87be7a8543213f5fa"}

# holochain_conductor_api_0_0_145 = {git = "https://github.com/guillemcordoba/holochain", package = "holochain_conductor_api", rev = "b455538b80228410417f372d828d07a7cfa9e4d5"}
# holochain_p2p_0_0_145 = {git = "https://github.com/guillemcordoba/holochain", package = "holochain_p2p", rev = "b455538b80228410417f372d828d07a7cfa9e4d5"}
# holochain_types_0_0_145 = {git = "https://github.com/guillemcordoba/holochain", package = "holochain_types", rev = "b455538b80228410417f372d828d07a7cfa9e4d5"}

# holochain_conductor_api_0_0_150 = {git = "https://github.com/guillemcordoba/holochain", package = "holochain_conductor_api", rev = "55264b3de477e0bd6bad678afa54aaa1236ff220"}
# holochain_p2p_0_0_150 = {git = "https://github.com/guillemcordoba/holochain", package = "holochain_p2p", rev = "55264b3de477e0bd6bad678afa54aaa1236ff220"}
# holochain_types_0_0_150 = {git = "https://github.com/guillemcordoba/holochain", package = "holochain_types", rev = "55264b3de477e0bd6bad678afa54aaa1236ff220"}

# holochain_conductor_api_0_0_152 = {git = "https://github.com/guillemcordoba/holochain", package = "holochain_conductor_api", rev = "24f88aede5ae770be73d3b690ac22b62d7ae7719"}
# holochain_p2p_0_0_152 = {git = "https://github.com/guillemcordoba/holochain", package = "holochain_p2p", rev = "24f88aede5ae770be73d3b690ac22b62d7ae7719"}
# holochain_types_0_0_152 = {git = "https://github.com/guillemcordoba/holochain", package = "holochain_types", rev = "24f88aede5ae770be73d3b690ac22b62d7ae7719"}

# NEW_VERSION add corresponding crates of the  new versions here


holochain_types_0_0_45 = {package = "holochain_types", version = "0.0.45"}

# NEW_VERSION add latest crates here # taken from commit instead this time
holochain_conductor_api_0_0_156 = {package = "holochain_conductor_api", version = "0.0.54"}
holochain_p2p_0_0_156 = {package = "holochain_p2p", version = "0.0.52"}
holochain_types_0_0_156 = {package = "holochain_types", version = "0.0.52"}

mr_bundle = {package = "mr_bundle", version = "0.0.13"}

lair_keystore_manager = {path = "../lair_keystore_manager"}

ascii = "1.0.0"
async-trait = "0.1.52"
enum_dispatch = "0.3.8"
log = "0.4.14"
portpicker = "0.1.1"
serde = {version = "1", features = ["derive"]}
serde-enum-str = "0.2"
serde_yaml = "0.8"
tauri = {version = "=1.0.4", features = ["api-all"]}
thiserror = "1.0.30"
url2 = "0.0.6"
