name: "publish"
on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: download caddy (Windows only)
        if: matrix.platform == 'windows-latest'
        run: |
          mkdir src-tauri/bins
          cd src-tauri/bins
          curl.exe --output caddy-x86_64-pc-windows-msvc.exe "https://caddyserver.com/api/download?os=windows&arch=amd64&idempotency=22435878078631"
      - name: download caddy (MacOS only)
        if: matrix.platform == 'macos-latest'
        run: |
          mkdir src-tauri/bins
          cd src-tauri/bins
          curl --output caddy.tar.gz "https://github-releases.githubusercontent.com/29207621/2490fd00-cfa4-11eb-810d-3baf663fb37f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20210720%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210720T140548Z&X-Amz-Expires=300&X-Amz-Signature=e04c41550edc4e2e6c6f6981ac38c9fb9fb916355bc234c4d63d561df7386e19&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=29207621&response-content-disposition=attachment%3B%20filename%3Dcaddy_2.4.3_mac_amd64.tar.gz&response-content-type=application%2Foctet-stream"
          gunzip -c caddy.tar.gz | tar xopf -
          mv caddy caddy-x86_64-apple-darwin
      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev squashfs-tools
      - name: install Caddy (ubuntu)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo apt-key add -
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
          sudo apt update
          sudo apt install caddy
      - name: install Holochain
        run: |
          cargo install --git https://github.com/holochain/holochain --rev 1eb5b70f64b2188e6ef0c876367838b8a6a2015d holochain --force
          cargo install lair_keystore --version 0.0.1-alpha.12
      - name: setup binaries (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sh scripts/setup-binaries.sh
      - name: setup binaries (macos only)
        if: matrix.platform == 'macos-latest'
        run: |
          HOLOCHAIN_PATH=$(which holochain)
          cp $HOLOCHAIN_PATH src-tauri/bins/holochain-x86_64-apple-darwin
          LAIR_PATH=$(which lair-keystore)
          cp $LAIR_PATH src-tauri/bins/lair-keystore-x86_64-apple-darwin
      - name: install app dependencies and build it
        run: yarn install && npm run tauri:build
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: true
