name: "test"
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  testbuild:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable
      - name: install webkit2gtk (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev squashfs-tools libgtksourceview-3.0-dev libappindicator3-dev patchelf librsvg2-dev libsqlcipher-dev

      - name: install Holochain
        run: |
          mkdir src-tauri/bins

          cargo install --version 0.2.3 lair_keystore
          LAIR_PATH=$(which lair-keystore)
          cp $LAIR_PATH src-tauri/bins/lair-keystore-x86_64-unknown-linux-gnu


          cargo install holochain --version 0.0.175 --locked --features db-encryption
          HOLOCHAIN_PATH=$(which holochain)
          cp $HOLOCHAIN_PATH src-tauri/bins/holochain-v0.0.175-x86_64-unknown-linux-gnu

          # NEW_VERSION: install new holochain version and copy its binary to the tauri path

      - name: install app dependencies and build it
        run: npm install && npm run build
