name: "test"
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  testbuild:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable
      - name: install webkit2gtk (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev squashfs-tools libgtksourceview-3.0-dev libappindicator3-dev patchelf librsvg2-dev libsqlcipher-dev
      - name: install Caddy (ubuntu)
        run: |
          sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
          sudo apt update
          sudo apt install caddy

      - name: install Holochain
        run: |
          mkdir src-tauri/bins

          cargo install --version 0.2.0 lair_keystore
          LAIR_PATH=$(which lair-keystore)
          cp $LAIR_PATH src-tauri/bins/lair-keystore-x86_64-unknown-linux-gnu

          CADDY_PATH=$(which caddy)
          cp $CADDY_PATH src-tauri/bins/caddy-x86_64-unknown-linux-gnu

          cargo install --locked --features db-encryption --git https://github.com/guillemcordoba/holochain.git --rev b455538b80228410417f372d828d07a7cfa9e4d5 holochain
          HOLOCHAIN_PATH=$(which holochain)
          cp $HOLOCHAIN_PATH src-tauri/bins/holochain-v0.0.145-x86_64-unknown-linux-gnu

          cargo install --locked --features db-encryption --git https://github.com/guillemcordoba/holochain.git --rev 55264b3de477e0bd6bad678afa54aaa1236ff220 holochain
          HOLOCHAIN_PATH=$(which holochain)
          cp $HOLOCHAIN_PATH src-tauri/bins/holochain-v0.0.150-x86_64-unknown-linux-gnu

          cargo install --locked --features db-encryption --git https://github.com/guillemcordoba/holochain.git --rev 24f88aede5ae770be73d3b690ac22b62d7ae7719 holochain
          HOLOCHAIN_PATH=$(which holochain)
          cp $HOLOCHAIN_PATH src-tauri/bins/holochain-v0.0.152-x86_64-unknown-linux-gnu

          cargo install --locked --features db-encryption --git https://github.com/guillemcordoba/holochain.git --rev 38b683d0009ada21a9d79f638ca2dc3986163bd9 holochain
          HOLOCHAIN_PATH=$(which holochain)
          cp $HOLOCHAIN_PATH src-tauri/bins/holochain-v0.0.154-x86_64-unknown-linux-gnu

          cargo install --locked --features db-encryption --git https://github.com/guillemcordoba/holochain.git --rev 1da41b41d49862597b4927780c771e44344d256d holochain
          HOLOCHAIN_PATH=$(which holochain)
          cp $HOLOCHAIN_PATH src-tauri/bins/holochain-v0.0.156-x86_64-unknown-linux-gnu

          # NEW_VERSION: install new holochain version and copy its binary to the tauri path

      - name: install app dependencies and build it
        run: npm install && npm run build
